# Use the same base image
FROM python:3.10

WORKDIR /app

COPY . /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["celery", "-A", "emailworker", "worker", "--loglevel=info"]
