version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: gunicorn --workers=3 --timeout 120 emailworker.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  celery:
    build: .
    container_name: celery_worker
    command: celery -A emailworker worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A emailworker beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started
